use_frameworks!

platform :ios, '10.0'

target 'GMSLibrary_Example' do
  pod 'GMSLibrary', :path => '../'

  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Messaging', :inhibit_warnings => true

  target 'GMSLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4', :inhibit_warnings => true
  end
end
